"""actualizacion modelos

Revision ID: aacf43710099
Revises: e3d49d353b7b
Create Date: 2026-02-24 21:17:32.757009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacf43710099'
down_revision = 'e3d49d353b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    op.create_table('whitelist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('whitelist_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('whitelist_pkey'))
    )
    # ### end Alembic commands ###
